### ISSUE TITLE
Have data from Amazon Pre-Processed (Due 20th)

### ISSUE THREAD

**Issue by ecdraayer** [syazdan25/SE17-Project#11]
- Looking and understanding the data and decide how we want to solve the problem from text-mining perspective!

- Pre-process it if needed.

http://jmcauley.ucsd.edu/data/amazon/

**Comment by ecdraayer** [comment]
-[] Do this

**Comment by MahnazBehroozi** [comment]
We preprocessed our dataset and has fed it into our system. The current dataset is the only labeled dataset we found up to now which has about 1000 samples. We are currently searching for more labeled datasets in order to make our learning model more powerful.
