### ISSUE TITLE
Brainstorm Session: Finalize 3 Implementations, assign who will investigate what, decide on programming language (Due 10th)

### ISSUE THREAD

**Issue by ecdraayer** [syazdan25/SE17-Project#12]
Have a Brainstorm session and come up with as many ways of implementation as possible. 
Pick the top 3, and decide who will investigate which implementation, final person will start pre-processing data.

- [x] 3 implementations
- [x] Programming Language
- [x] Who will Investigate What

**Comment by syazdan25** [comment]
Programming language: Python
Tool: Flask
Developing a web application
