### ISSUE TITLE
Explore Different Sentiment Analysis Approach (Due 15th)

### ISSUE THREAD

**Issue by ecdraayer** [syazdan25/SE17-Project#14]
- [x] iFeel
- [x] Deeply Moving
- [x] Python NLTK
- [ ] R, TM
- [ ] GATE

**Comment by syazdan25** [comment]
Lets choose one sentiment analysis method each person. I choose to study iFeel.
I will share a document with some reviews and lets label those reviews using the method we our method.
Please comment your choice of method.

**Comment by Sanand007** [comment]
I am studying paper written on Stanford sentiment analysis tool by their developers.
