### ISSUE TITLE
Brainstorming on the steps we want to take toward Feb. milestone (Due 6th)

### ISSUE THREAD

**Issue by MahnazBehroozi** [syazdan25/SE17-Project#15]
We must gather together to decide different phases of our project and organize our steps due date.

This meeting should be before Feb. 7.

**Comment by syazdan25** [comment]
We can use the dataset of amazon reviews at http://jmcauley.ucsd.edu/data/amazon/ but the reviews are not labelled.
at https://www.cs.jhu.edu/~mdredze/datasets/sentiment/ we have labelled reviews.
