### ISSUE TITLE
Writing a program using Python and NLTK

### ISSUE THREAD

**Issue by MahnazBehroozi** [syazdan25/SE17-Project#19]

**Comment by syazdan25** [comment]
http://www.laurentluce.com/posts/twitter-sentiment-analysis-using-python-and-nltk/
good stuff!!

**Comment by Sanand007** [comment]
Program written. Need to smoothen it.

**Comment by Sanand007** [comment]
Uploaded python nltk code on GitHub.

**Comment by syazdan25** [comment]
uploaded Web page code. Lets try and integrate the NLTK code with web page.
