### ISSUE TITLE
List of papers for literature survey by Jan 26th

### ISSUE THREAD

**Issue by syazdan25** [syazdan25/SE17-Project#3]

**Comment by Sanand007** [comment]
Reading 
http://nlp.stanford.edu/~socherr/EMNLP2013_RNTN.pdf
http://cs229.stanford.edu/proj2012/ChakankarVenuturimilliMathur-SentimentAnalysis.pdf

**Comment by syazdan25** [comment]
Mahnaz-
 -Who cares about sarcastic tweets? Investigating the impact of sarcasm on sentiment analysis
                http://www.lrec-conf.org/proceedings/lrec2014/pdf/67_Paper.pdf

              - Challenges in Sentiment Analysis
                 http://saifmohammad.com/WebDocs/sentiment-challenges.pdf

              - Fake It Till You Make It: Reputation, Competition, and Yelp Review Fraud     
                 http://pubsonline.informs.org/doi/pdf/10.1287/mnsc.2015.2304

Shama-
Feldman, Ronen. "Techniques and applications for sentiment analysis." Communications of the ACM 56.4 (2013): 82-89.
Serrano-Guerrero, Jesus, et al. "Sentiment analysis: a review and comparative analysis of web services." Information Sciences 311 (2015): 18-38.
or
Choo, Euijin, Ting Yu, and Min Chi. "Detecting opinion spammer groups through community discovery and sentiment analysis." IFIP Annual Conference on Data and Applications Security and Privacy. Springer International Publishing, 2015.
